POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Rodrigo Sena",
    "email": "rodrigo@teste.com",
    "password": "123123"
}

###
GET http://localhost:3333/profile/2cc89bec-13f8-4d32-b5e9-6058edc3046a